payback:
  topic:
    order-canceled: bz_refund_completed_gmkt
    order-created: bz_carbon_order_created
  consumers:
    order-created-listener:
      group-id: payback-cashback-group
      concurrency: 25
    order-canceled-ssgpoint-listener:
      group-id: ssgpoint-canceled-gmkt-group
      concurrency: 1