spring:
  application.name: payback-consumer
  kafka:
    consumer:
      group-id: payback-group
      auto-offset-reset: latest
      enable-auto-commit: true
      bootstrap-servers:
        listener-1: hscdv06gm:9092,hscdv07gm:9092,hscdv08gm:9092,hscdv09gm:9092,hscdv10gm:9092
        listener-2: satbroker-01-kafka-dev-staturn:9092,satbroker-02-kafka-dev-staturn:9092,satbroker-03-kafka-dev-staturn:9092,satbroker-04-kafka-dev-staturn:9092,satbroker-05-kafka-dev-staturn:9092

# KafKa Configuration
kafka:
  consumer:
    concurrency:
      gmarket:
        order-created: 25 #dev: POD 2개 가정시
      gmarket-global:
        order-created: 8 #dev: POD 2개 가정시
    topic:
      gmarket:
        order-created-event: bz_carbon_order_created_gmkt
      gmarket-global:
        order-created-event: bz_carbon_order_created_gg

payback:
  topic:
    order-created: bz_carbon_order_created
    order-canceled-gmkt: bz_refund_completed_gmkt
    order-canceled-iac: bz_claim_order_cancel_iac
  consumers:
    order-created-cashback-listener:
      group-id: payback-cashback-group
    order-canceled-ssgpoint-gmkt-listener:
      group-id: ssgpoint-canceled-gmkt-group
    order-canceled-ssgpoint-iac-listener:
      group-id: ssgpoint-canceled-iac-group
apis:
  payback:
    url: "http://payback-api-dev.gmarket.co.kr"