spring:
  config.activate.on-profile: "gmarket"
  application.name: payback-consumer
    kafka:
      consumer:
        group-id: payback-group
        auto-offset-reset: latest
        enable-auto-commit: true
        bootstrap-servers:
          listener-1: hscdv06gm:9092,hscdv07gm:9092,hscdv08gm:9092,hscdv09gm:9092,hscdv10gm:9092
          order: satbroker-01-kafka-dev-staturn:9092,satbroker-02-kafka-dev-staturn:9092,satbroker-03-kafka-dev-staturn:9092,satbroker-04-kafka-dev-staturn:9092,satbroker-05-kafka-dev-staturn:9092
---
spring:
  config.activate.on-profile: "auction"
  application.name: payback-consumer
    kafka:
      consumer:
        group-id: payback-group
        auto-offset-reset: latest
        enable-auto-commit: true
        bootstrap-servers:
          listener-1: hscdv06gm:9092,hscdv07gm:9092,hscdv08gm:9092,hscdv09gm:9092,hscdv10gm:9092
          order: hscdv06gm:9092,hscdv07gm:9092,hscdv08gm:9092,hscdv09gm:9092,hscdv10gm:9092
---

apis:
  payback:
    url: "http://payback-api-dev.gmarket.co.kr"