
kafka.consumer.concurrency.order.created: 25

payback:
  topic:
    order-created: bz_carbon_order_created
  consumers:
    order-created-cashback-listener:
      group-id: payback-cashback-group
    order-canceled-ssgpoint-gmkt-listener:
      group-id: ssgpoint-canceled-gmkt-group
    order-canceled-ssgpoint-iac-listener:
      group-id: ssgpoint-canceled-iac-group