
kafka.consumer.concurrency.order.created: 25

payback:
  topic:
    order-created: bz_carbon_order_created
  consumers:
    order-created-cashback-listener:
      group-id: payback-cashback-group
    order-created-ssgpoint-listener:
      group-id: payback-ssgpoint-group
