spring:
  config.activate.on-profile: "gmarket"
---
spring:
  config.activate.on-profile: "auction"
---

com.ebaykorea.payback.scheduler:
  data:
    initialDelay: 10 #TimeUnit.MINUTES
    fixedDelay: 10 #TimeUnit.MINUTES
    maxTryCount: 5
