saturn:
  application:
    tenantId: "auction"
  datasource:
    appName: PAYBACK_APP
    userName: discountapp
    tenant: auctiondev

apis:
  payback:
    url: "http://payback-api-dev.auction.co.kr"
  quilt:
    url: "https://quilt-overmind-dev.auction.co.kr/api"
    user-id-query-path: "/v1/user-token/member-id"
  smile-cash:
    url: "https://devcashpartnerapi.mysmilepay.com"