saturn:
  application:
    tenantId: "gmarket"
  datasource:
    appName: PAYBACK_API
    userName: daemon_app
    tenant: gmarketdev #개발: gmarketdev, 운영: gmarket

apis:
  payback:
    url: "http://payback-api-dev.gmarket.co.kr"
  quilt:
    url: "https://quilt-overmind-dev.gmarket.co.kr/api"
    user-id-query-path: "/user-token/cust-no"