spring:
  application.name: payback-consumer
  kafka:
    consumer:
      group-id: payback-group
      auto-offset-reset: latest
      enable-auto-commit: true
      bootstrap-servers: satbroker-01-kafka-dev-staturn:9092,satbroker-02-kafka-dev-staturn:9092,satbroker-03-kafka-dev-staturn:9092,satbroker-04-kafka-dev-staturn:9092,satbroker-05-kafka-dev-staturn:9092

saturn:
  application:
    domain: "payback"
    tenantid: "gmarket"
    api-info:
      name: "payback-api"
      api-package: "com.ebaykorea.payback.api"
      version:
        major: "v1"
        full: "v1.0.0"

kafka.consumer.concurrency.order.created: 25

payback:
  topic:
    order-created: bz_carbon_order_created
  consumers:
    order-created-cashback-listener:
      group-id: payback-cashback-group
    order-created-ssgpoint-listener:
      group-id: payback-ssgpoint-group
