spring:
  config.activate.on-profile: "gmarket"
  kafka:
    consumer:
      group-id: payback-group
      auto-offset-reset: latest
      enable-auto-commit: true
      bootstrap-servers:
        listener-1: localhost:9092
        order: localhost:9092
---
spring:
  config.activate.on-profile: "auction"
  kafka:
    consumer:
      group-id: payback-group
      auto-offset-reset: latest
      enable-auto-commit: true
      bootstrap-servers:
        listener-1: localhost:9092
        order: localhost:9092
---

apis:
  payback:
    url: "http://payback-api-dev.gmarket.co.kr"