saturn:
  application:
    tenantId: "auction"
  datasource:
    appName: PAYREWARD_APP
    userName: escrowapp
    tenant: auction
    configs:
      - beanName: "maindb2_readDataSource"
        hikariCp:
          minimumIdle: 1

apis:
  reward:
    url: "http://payreward-api-av.auction.co.kr"
  order:
    url: "http://order-api-av.gmarket.co.kr/v1" #TODO
  club:
    url: "https://clubapi.gmarket.co.kr" #TODO
  payment:
    url: "http://payment-api-av.gmarket.co.kr" #TODO
  transaction:
    url: "http://transaction-api-av.gmarket.co.kr/v1" #TODO
  quilt:
    url: "https://quilt-overmind.auction.co.kr/api"
    user-id-query-path: "/v1/user-token/member-id"