
saturn:
  application:
    domain: "payback"
    tenantid: "gmarket"
    api-info:
      name: "payback-api"
      api-package: "com.ebaykorea.payback.api"
      version:
        major: "v1"
        full: "v1.0.0"
    datasource:
      appName: PAYREWARD_APP
      userName: payback_app
      tenant: gmarket #개발: gmarketdev, 운영: gmarket

apis:
  reward:
    url: "http://rewardservice.gmarket.co.kr"
  order:
    url: "http://order-api-av.gmarket.co.kr/v1"
  club:
    url: "https://clubapi.gmarket.co.kr"
  payment:
    url: "http://payment-api-av.gmarket.co.kr"
  transaction:
    url: "http://transaction-api-av.gmarket.co.kr/v1"
  quilt:
    url: "https://quilt-overmind.gmarket.co.kr/api"

payback.dcm.access.enable: true