
apis:
  smileclub:
    url: "http://smileclubapi.gmarket.co.kr"
  ssgpoint:
    url: "https://authmemapi.shinsegaepoint.com"
  teams:
    url: "https://gmarketcorp.webhook.office.com"

#spring.jpa.hibernate.default_schema: O_PAYREWARD
spring:
  batch:
    jdbc:
      table-prefix: O_PAYREWARD.BATCH_
    job:
      enabled: false

ssgpoint:
  auth-info:
    gmarket:
      memberKey: 'S001'
      clientId: '49E615F309BC23C5CA7E4603E2036977'
      apiKey: '067B23515D3077BE30F66A0E4E081B99'
      encryptKey: 'CDC99D6D86C2BE9B494FAAE6F0769DBD'
      encryptIv: '243B73255BB5E245'
      decryptInstance: 'gmarket'
      branchId: 'B200042500'
    auction:
      memberKey: 'S002'
      clientId: '3C24A0D1FADA47F07F9A79D30D4C9A2E'
      apiKey: 'C9409188BBFC5D635D505BD2AC98EFCB'
      encryptKey: 'D2F413909370347B64D4100F4C039741'
      encryptIv: 'B48FD506BD1E4410'
      decryptInstance: 'auction-aes'
      branchId: 'B200042502'
  batch:
    fetchSize: 100         #ItemReader에 읽는 Row수
    chunkSize: 10         #Chunk 처리단위
  scheduler:
    daily:
      crontab: "0 0 2 * * *" #매일 2시 실행
    target:
      crontab: "30 */5 9-23 * * *" #5분30초
    recover:
      crontab: "0 */60 12-22 * * *" #1시간 간격


