saturn:
  application:
    tenantId: "auction"
  datasource:
    appName: PAYREWARD_APP
    userName: escrowapp
    tenant: auction

apis:
  reward:
    url: "http://payreward-api-dev.auction.co.kr"
  order:
    url: "http://order-api-dev.gmarket.co.kr/v1" #TODO
  club:
    url: "https://clubapi-dev.gmarket.co.kr" #TODO
  payment:
    url: "http://payment-api-dev.gmarket.co.kr" #TODO
  transaction:
    url: "http://transaction-api-dev.gmarket.co.kr/v1" #TODO
  quilt:
    url: "https://quilt-overmind-dev.auction.co.kr/api"
    user-id-query-path: "/v1/user-token/member-id"