###################################################
# LOCAL
###################################################
server:
  port: 8080

spring:
  application:
    name: payback
  profiles:
    include: custom
  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      inspect_stacktrace: true
      naming_physical_strategy: org.hibernate.boot.entity.naming.PhysicalNamingStrategyStandardImpl  #naming.physical-strategy

logging:
  pattern:
    console: "[%-20(%cyan(%date{HH:mm:ss.SSS})] [%thread]) [%X{moa.requestid}] %highlight(%-5level) %magenta(%marker|%logger{36}): %msg%n%rEx" # console pattern
  level:
    root: INFO
    com.ebaykorea.saturn: WARN
    MoAAppender: INFO
    MoALogger: INFO
    com.ebaykorea.payback.infrastructure.gateway.client: INFO

###################################################
# feign Configurations
###################################################
feign:
  httpclient:
    enabled: true
    maxConnections: 1000
    maxConnectionsPerRoute: 100
  circuitbreaker.enabled: false
  client.config:
    default:
      connectTimeout: 5000  # resilience4j timeoutDuration 보다 커야 함.
      readTimeout: 5000

# Resilience4j Configurations
# 설정관련 - https://wiki.ebaykorea.com/display/ANNA/Resilience4j
resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 500
    instances:
      retryApi: # retry name
        baseConfig: default

###################################################
# Saturn Configurations
###################################################
saturn:
  groupId: com.ebaykorea
  artifactId: payback
  moa:
    domainGroup: payreward
    domain: payback.api
    host: http://moafw2.ebaykorea.com/bulk
  application:
    domain: "payback"
    tenantid: "gmarket"
    api-info:
      name: "payback-api"
      api-package: "com.ebaykorea.payback.api"
      version:
        major: "v1"
        full: "v1.0.0"
  datasource:
    appName: PAYREWARD_APP
    userName: payback_app
    tenant: gmarket #개발: gmarketdev, 운영: gmarket
    configs:
      - beanName: "tiger_readDataSource"
        hikariCp:
          minimumIdle: 1

###################################################
# Common Management Configurations - DO NOT EDIT
###################################################
management:
  server.port: 8081
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS
  health:
    db.enabled: false
    redis.enabled: false
  metrics:
    export.prometheus.enabled: true
    cache.instrument: true
    web.server.request.auto-time.enable: false