
apis:
  reward:
    url: "http://rewardservice.gmarket.co.kr"
  order:
    url: "http://order-api.gmarket.co.kr/v1"
  club:
    url: "https://clubapi.gmarket.co.kr"
  payment:
    url: "http://payment-api.gmarket.co.kr"
  transaction:
    url: "http://transaction-api.gmarket.co.kr/v1"
  quilt:
    url: "https://quilt-overmind.gmarket.co.kr/api"

payback.dcm.access.enable: true