spring:
  config.activate.on-profile: "gmarket"
---
spring:
  config.activate.on-profile: "auction"
---

com.ebaykorea.payback.scheduler:
  data:
    initialDelay: 10 #TimeUnit.MINUTES
    fixedDelay: 10 #TimeUnit.MINUTES
    maxTryCount: 5
  event-reward:
    start-date: "" #yyyymmdd 형식
    end-date: ""
  mass-save:
    initialDelay: 10 #TimeUnit.SECONDS
    fixedDelay: 10 #TimeUnit.SECONDS
    max-rows: 3000
    max-retry-count: 5
  mass-save-check:
    initialDelay: 1 #TimeUnit.MINUTES
    fixedDelay: 1 #TimeUnit.MINUTES