saturn:
  application:
    tenantId: "auction"
  datasource:
    appName: PAYREWARD_APP
    userName: escrowapp
    tenant: auction

apis:
  payback:
    url: "http://payback-api.auction.co.kr"
  quilt:
    url: "https://quilt-overmind.auction.co.kr/api"
    user-id-query-path: "/v1/user-token/member-id"
  smile-cash:
    url: "https://iaccashpartnerapi.mysmilepay.com"